/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppStatementsRouteImport } from './routes/app.statements'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLoansRouteImport } from './routes/app.loans'
import { Route as AppInvestmentsRouteImport } from './routes/app.investments'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppDepositRouteImport } from './routes/app.deposit'
import { Route as AppCardRouteImport } from './routes/app.card'
import { Route as AdminAccountIdRouteImport } from './routes/admin.account.$id'

const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppCardRoute = AppCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AppRoute,
} as any)
const AdminAccountIdRoute = AdminAccountIdRouteImport.update({
  id: '/account/$id',
  path: '/account/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/locked': typeof LockedRoute
  '/app/card': typeof AppCardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/home': typeof AppHomeRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/loans': typeof AppLoansRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/support': typeof AppSupportRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/account/$id': typeof AdminAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/locked': typeof LockedRoute
  '/app/card': typeof AppCardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/home': typeof AppHomeRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/loans': typeof AppLoansRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/support': typeof AppSupportRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/account/$id': typeof AdminAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/locked': typeof LockedRoute
  '/app/card': typeof AppCardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/home': typeof AppHomeRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/loans': typeof AppLoansRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/support': typeof AppSupportRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/account/$id': typeof AdminAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/locked'
    | '/app/card'
    | '/app/deposit'
    | '/app/home'
    | '/app/investments'
    | '/app/loans'
    | '/app/notifications'
    | '/app/settings'
    | '/app/statements'
    | '/app/support'
    | '/app/transactions'
    | '/admin/'
    | '/admin/account/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/locked'
    | '/app/card'
    | '/app/deposit'
    | '/app/home'
    | '/app/investments'
    | '/app/loans'
    | '/app/notifications'
    | '/app/settings'
    | '/app/statements'
    | '/app/support'
    | '/app/transactions'
    | '/admin'
    | '/admin/account/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/locked'
    | '/app/card'
    | '/app/deposit'
    | '/app/home'
    | '/app/investments'
    | '/app/loans'
    | '/app/notifications'
    | '/app/settings'
    | '/app/statements'
    | '/app/support'
    | '/app/transactions'
    | '/admin/'
    | '/admin/account/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  LockedRoute: typeof LockedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/statements': {
      id: '/app/statements'
      path: '/statements'
      fullPath: '/app/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loans': {
      id: '/app/loans'
      path: '/loans'
      fullPath: '/app/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investments': {
      id: '/app/investments'
      path: '/investments'
      fullPath: '/app/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/card': {
      id: '/app/card'
      path: '/card'
      fullPath: '/app/card'
      preLoaderRoute: typeof AppCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/account/$id': {
      id: '/admin/account/$id'
      path: '/account/$id'
      fullPath: '/admin/account/$id'
      preLoaderRoute: typeof AdminAccountIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountIdRoute: typeof AdminAccountIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountIdRoute: AdminAccountIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCardRoute: typeof AppCardRoute
  AppDepositRoute: typeof AppDepositRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppLoansRoute: typeof AppLoansRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCardRoute: AppCardRoute,
  AppDepositRoute: AppDepositRoute,
  AppHomeRoute: AppHomeRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppLoansRoute: AppLoansRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  LockedRoute: LockedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
